apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: cloudflow-eks-w1-129
  namespace: nethopper 
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/cloudflow.git//iac/tf/aws/eks-aws
    vars:
    - key: region
      value: us-west-1
    - key: cluster-name-suffix
      value: eks-w1-129
    - key: k8s-version
      value: "1.29"
  writeConnectionSecretToRef:
    namespace: default
    name: cloudflow-eks-w1-129
  providerConfigRef:
    name: awsconfig
