apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: aks-azure-central
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/cloudflow.git//iac/tf/azure/aks
    vars:
    - key: region
      value: centralus
    - key: cluster-name-suffix
      value: aks-central
    varFiles:
    - source: SecretKey
      secretKeyRef:
        namespace: default
        name: vpc-azure-tfvars
        key: terraformtfvars
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-aks-azure-central
  providerConfigRef:
    name: azureconf
