apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: cloudflow-eks-123
  namespace: nethopper
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/cloudflow.git//iac/tf/aws/eks-aws
    vars:
    - key: region
      value: us-east-2
    - key: cluster-name-suffix
      value: eks-129
    - key: k8s-version
      value: "1.29"
  writeConnectionSecretToRef:
    namespace: default 
    name: cloudflow-eks-129
  providerConfigRef:
    name: awsconfig
