apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: aks-azure
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/cloudflow.git//iac/tf/azure/aks
    # NOTE: Dont' define variables that you don't use, because this causes TF warning that could complicate Crossplane status
#     vars:
#     - key: region
#       value: westus2
    varFiles:
    - source: SecretKey
      secretKeyRef:
        namespace: default
        name: vpc-azure-tfvars
        key: terraformtfvars
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-aks-azure
  providerConfigRef:
    name: azureconf
