apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: vpc-aws
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/kaops.git//demo/iac/aws-vpc
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-vpc-aws
  providerConfigRef:
    name: awsconfig
